version: "3.9"

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=1
      - SECRET_KEY=97e9f44d46c60e9d02d9f2182a95f8b1
      - CSRF_SECRET_KEY=c9fc0db43170040c73f743d7c8867101
      - PUBLIC_KEY=6Lckc3cpAAAAAKkrrEtJkMuJhvga1xTeZoPRiT7W
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_USERNAME=systemsprogramming95@gmail.com
      - MAIL_PASSWORD=vpwbzhsljrzkerwo
      - ODBC_CONN_STR=DRIVER={ODBC Driver 17 for SQL Server};SERVER=sqlserver,14330;DATABASE=newx;UID=sa;PWD=JBS@12345678
    depends_on:
      - sqlserver
      - rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:14330"
    environment:
      SA_PASSWORD: "JBS@12345678"
      ACCEPT_EULA: "Y"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5673"
      - "15672:15672"
    restart: unless-stopped
