"""Initial migration

Revision ID: fd1719e067e2
Revises: c1d2845f727b
Create Date: 2024-11-21 10:38:22.910817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1719e067e2'
down_revision = 'c1d2845f727b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('userId')

    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.drop_column('salt')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
